name: Node CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Upgrade NPM
        run: npm install -g npm
      - name: Get tag
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build library
        run: npm ci
      - run: npm run build

      - run: npm run release  ${{ env.RELEASE_VERSION }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: .
          message: 'Your commit message'
          tag: '${{ env.RELEASE_VERSION }} --force'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
