name: Node CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Get tag
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build
        run: npm ci && npm run build && npm run release ${{ env.RELEASE_VERSION }}
      - name: Commit & Push
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add -A
          git commit -m "Automated report"
          git push
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
