name: Node CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Get tag
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: test
        run: echo ${{env.RELEASE_VERSION }}
      - name: Build
        run: |
          npm ci
          npm run build
          npm run release ${{ env.RELEASE_VERSION }}
      - name: Publish
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add -A &&
          git commit -m "release Version: ${{ env.RELEASE_VERSION }}"
          git push &&
          git tag ${{ env.RELEASE_VERSION }} --force &&
          git push --tag --force
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
