name: Continuous Integration (CI)

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Build
        run: |
          npm ci
          npm run build
          npm run set-version ${{ github.ref_name }}
      - name: Publish
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add -A
          git commit -m "[release] Version: ${{ github.ref_name }}"
          git push
          git tag ${{ github.ref_name }} --force
          git push --tag --force
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
