name: Node CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Get tag
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Build
        run: npm ci && npm run build && npm run release ${{ env.RELEASE_VERSION }}
      - name: Publish
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'release Version: ${{ env.RELEASE_VERSION }}'
          tag: ${{ env.RELEASE_VERSION }} --force'
          tag_push: '--force'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
